version: 2
references:
  commands:
    setup_repo: &setup_repo
      name: "Git clone"
      command: "git clone $CIRCLE_REPOSITORY_URL /tmp/_circleci_local_build_repo"
    install_python: &install_python
      name: "Install Python"
      command: "sudo killall -9 apt-get || true && \
      sudo apt update && \
      sudo apt install -y python3 python3-pip"
    exec_upgrade_pip: &exec_upgrade_pip
      name: "Upgrade pip, wheel and setuptools"
      command: "sudo pip3 install -U pip wheel setuptools"
    install_cwl_runner: &install_cwl_runner
      name: "Install cwl-runner"
      command: "sudo pip3 install cwltool cwl-runner cwltest"
    run_test: &run_test
      name: "Run test"
      command: "sudo cwltest --verbose --test cwltest.yml"


jobs:
  build:
    working_directory: /tmp/cwl_test
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: *setup_repo
      - checkout
      - run: *install_python
      - run: *exec_upgrade_pip
      - run: *install_cwl_runner
      - run: *run_test
  buildlocal:
    working_directory: /tmp/cwl_test
    machine: true
    steps:
      - run: *setup_repo
      - checkout
      - run: *install_python
      - run: *exec_upgrade_pip
      - run: *install_cwl_runner
      - run: *run_test
